databases:
  - name: url-guard-db
    plan: free
    databaseName: url_guard
    user: url_guard_user

services:
  - type: web
    name: url-guard
    env: docker
    plan: free
    branch: main
    repo: https://github.com/praneethyelchuru15-dotcom/URL-GUARD
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: url-guard-db
          property: connectionString
